### ISSUE TITLE
NameError: name 'basestring' is not defined

### ISSUE THREAD

**Issue by hdb3** [sjjf/md_server#14]
python3 needs 'str' not 'basestring' at around line 470 in mdserver/server.py

**Comment by sjjf** [comment]
Yeah, I haven't been focused on supporting python3 as yet - I'm doing a major rewrite which will include moving over to python3, but it's been delayed by Real Life(tm)

That said, this is very simple code and it turns out to be dead easy to do a good enough job of making it work. I've just pushed a new stable/0.5 branch that includes a fix for this issue - I've tested it on python 3.6 (Ubuntu Bionic) and it all behaves as expected. I'll be maintaining this branch for the forseeable future without any significant functional changes.

Can you confirm that this works in your environment?

**Comment by hdb3** [comment]
Hi Simon
I've not tried your new release but I can tell you that with the one line fix the old release worked for me on Ubuntu 20.04, python 3.8.2, including systemd integration.
As an aside tho, the suggestions on libvirt xml bios (ec2.....) to get ubuntu cloud working failed dismally - i.e. did not induce any network activity at all from the VM.  This was using 20.04 cloud images.  Centos8 cloud works fine tho, with no BIOS fiddles required.  It would be great to find a way to enable ubuntu server in this environment.....

**Comment by sjjf** [comment]
Yeah, the ec2 "fix" is a serious hack. I'm surprised it resulted in such a serious failure, but I'm not surprised it's unreliable . . . Exactly what happens will depend on the version of cloud-init that's installed and how it's configured - CentOS tends to be more conservative about following upstream than Ubuntu, so it may be using an older version. The ec2 UUID thing came from reading the cloud-init code to see how it recognised that it was running in AWS, so it's possible the code has changed enough to break it. However, updating the image as documented /should/ work, since it bypasses cloud-init's attempt to figure out if it should run.

The proper fix is to talk to the cloud-init devs to get md_server properly supported - this is on my todo list, but I haven't had a chance to chase that up.

I'll close this issue, since the core problem is resolved. If you want to raise another issue regarding the ec2/cloud-init problems feel free, and I'll take a closer look.
