### ISSUE TITLE
No license file

### ISSUE THREAD

**Issue by jamescassell** [sjjf/md_server#6]
I couldn't find a license in the source. Did I miss it? Under which terms may I use this code?

**Comment by sjjf** [comment]
Wow, I just realised you're right - no LICENSE file or anything talking about the licensing terms.

I /think/ I've rewritten enough of the code to be able to say that this repository can be relicensed without reference to the previous author, but I can't give any hard legal guarantee - if you're looking for the kind of certainty that a corporate legal department might want I certainly can't give that.

Outside that, I'll add a LICENSE file that makes it clear that this is licensed under the GPLv3 or later, with the standard terms, and I'll try and contact the previous author to confirm that this is okay.

Thanks for bringing this up.

**Comment by sjjf** [comment]
Okay, after discussion with my employer I've changed that to an MIT license instead of GPLv3 - given this is rather more permissive I expect that there's no issue with this choice from your end.

Simon

**Comment by sjjf** [comment]
ugh - closed feels like the wrong conclusion . . .

**Comment by sjjf** [comment]
. . . and it's the only option. Whatever.

Can you see I'm new to this? ;-)

**Comment by jamescassell** [comment]
Thanks for the update! I appreciate the liberal license... I'll try to get this packaged into Fedora... Were you able to contact the original author(s)?

**Comment by sjjf** [comment]
Not yet, though I've checked the code and there's very little that's not been rewritten since I originally forked it. I'll have a shot at contacting the original author today.

Great to hear that you're looking to package mdserver in Fedora! My next goal is to get cloud-init to recognise it as a valid data source, and I expect having mdserver packaged in Fedora will make that easier to justify.

Simon

**Comment by sjjf** [comment]
Aha, let's try this:

@xchandan could you please comment on this licensing question regarding your old code? As I've noted, I believe I've rewritten almost everything from your original repo, but there are still snippets here and there that haven't changed - would be okay with licensing any remaining code of yours using the MIT license? At present the LICENSE.txt file I've added lists my employer as copyright holder - if you'd like I can add your name to the license as well in order to accord you equal status.

Thanks,
Simon Fowler

**Comment by sjjf** [comment]
@jamescassell I've now gone through and removed any remaining files that had potential copyright issues, so as of version 0.5.0 it should be clearly licensed as per the LICENSE.txt file.

@xchandan I've retained mention of you in the contributors.txt file as the author of the original version - as I said I'm happy to add you to the LICENSE.txt file if you'd like that level of recognition, though at present there's no remaining code from your original version.

Simon

**Comment by jamescassell** [comment]
Not sure that last change is legit... there's no hurry, it might be better to wait for the okay from the original author.

**Comment by sjjf** [comment]
How is removing unused code not legit? The only actual code rewrite in the last change was moving from a standalone script to using the setuptools entry_points mechanism to auto-generate the mdserver executable, which is arguably a cleaner approach, and makes it easier for me to add other entry points, which I'm considering for some additional future functionality.

I'm not really in a hurry, I just have time to address this now and I figured I should . . .

**Comment by jamescassell** [comment]
Fair enough
